# Generated by Django 3.2.23 on 2024-02-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20240221_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('other_team', models.CharField(blank=True, max_length=254, null=True)),
                ('team_news_only', models.BooleanField(default=False)),
                ('favourite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.team')),
            ],
        ),
    ]
