# Generated by Django 3.2.23 on 2024-02-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240212_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='home_away',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Away', 'Away')], max_length=254, null=True, verbose_name='Home/Away'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=254, null=True),
        ),
    ]
